name: Crear archivo y usar valor

on:
 workflow_dispatch:
jobs:
  LoginJira:
    runs-on: ubuntu-latest
    steps:
      - name: Login JIRA
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
           
      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: E0
          issuetype: "Build"
          summary: "Pendiente de aprobar PullRequest ${{ github.repository }}"
          description: "Compare branch"
          
