name: "Send-email"

on:
  workflow_dispatch:

   inputs:
      from:
        description: "The sender sending the e-mail"
        required: true
      to:
        description: "The addressee who should receive the e-mail"
        required: true
      subj:
        description: "Description Email"
        required: true
env:
    FROM:   ${{ github.event.inputs.from }}
    TO:     ${{ github.event.inputs.to }}
    SUBJET: ${{ github.event.inputs.subj }}       

jobs:
  Send-email:
    runs-on: 
        - self-hosted
        - devops-plat-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'  # Puedes especificar la versión de Python que necesites
  
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Send email
        id: send_email
        working-directory: ./actions
        run: |
          python -u send-mail-frunction.py ${{ env.FROM}} ${{  env.TO }} ${{ env.SUBJET }}

      - name: Show result
        if: steps.end_email.outcome == 'success'
        run: |
          echo "Email sent successfully!"

      - name: Show error
        if: steps.end_email.outcome == 'failure'
        run: |
          echo "Error sending e-mail."
