name: CI/CD
on:
 workflow_dispatch:

jobs:
  create_issue_and_save_to_env:
    runs-on: ubuntu-latest
    steps:
      - name: Crear issue y guardar su ID
        id: create
        run: |
          # Tu comando para crear el issue aquí
          echo "::set-output name=issue::valor_del_issue_generado"

      - name: Guardar ISSUE_ID en archivo .env
        run: |
          echo "ISSUE_ID=${{ steps.create.outputs.issue }}" > .env
          cat .env  # Solo para verificar que el archivo .env se ha creado correctamente
