name: Crear archivo .txt y usar valor

on:
  push:
    branches:
      - main

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo .txt y guardar valor
        run: |
          echo "ISSUE_VALUE=${{ steps.create.outputs.issue }}" > issue_value.txt
          cat issue_value.txt  # Solo para verificar que se creó correctamente
        id: save_value

  use_value:
    runs-on: ubuntu-latest
    needs: create_file
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Leer valor del archivo
        run: |
          ISSUE_VALUE=$(<issue_value.txt)
          echo "El valor de ISSUE_VALUE es $ISSUE_VALUE"

