name: Crear archivo y usar valor

on:
  push:
    branches:
      - main

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo .txt y guardar valor
        run: |
          echo "ISSUE_VALUE=${{ steps.create.outputs.issue }}" > $GITHUB_WORKSPACE/issue_value.txt
          cat $GITHUB_WORKSPACE/issue_value.txt  # Verificar que se creó correctamente
        id: save_value
        continue-on-error: true

  use_value:
    runs-on: ubuntu-latest
    needs: create_file
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Leer valor del archivo
        run: |
          ISSUE_VALUE=$(cat $GITHUB_WORKSPACE/issue_value.txt | grep -oP '(?<=ISSUE_VALUE=).*')
          echo "El valor de ISSUE_VALUE es $ISSUE_VALUE"


