name: Crear archivo .env en ruta raíz de la carpeta app

on:
  push:
    branches:
      - main

jobs:
  create_env_file:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo .env
        run: |
          echo "ISSUE_ID=valor_del_issue_generado" > ./ .env
          cat app/.env  # Solo para verificar que se creó correctamente

  use_env_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Cargar variables del archivo .env
        run: |
          source ./ .env

      # Ejemplo de cómo utilizar las variables del archivo .env
      - name: Mostrar el valor de ISSUE_ID
        run: echo "El valor de ISSUE_ID es $ISSUE_ID"
